import { chromium } from 'playwright-core';
const b=await chromium.launch({executablePath:'/opt/pw-browsers/chromium-1194/chrome-linux/chrome'});
const pg=await b.newPage({viewport:{width:1400,height:1000}});
const errs=[]; pg.on('pageerror',e=>errs.push(e.message.slice(0,160)));
await pg.goto('http://localhost:4215/',{waitUntil:'networkidle'});
await pg.getByText('Entrar no painel').click({force:true}); await pg.waitForTimeout(400);
await pg.locator('nav').getByRole('button',{name:/Comercial/}).click({force:true}); await pg.waitForTimeout(500);
await pg.getByRole('button',{name:/Anotar/}).click({force:true}); await pg.waitForTimeout(300);
const abriu = await pg.getByText(/Anotações ·/).count();
await pg.getByTitle('retangulo').click({force:true});
const svg = pg.locator('svg[viewBox="0 0 1000 1414"]').first();
const box = await svg.boundingBox();
await pg.mouse.move(box.x+box.width*0.3, box.y+box.height*0.2);
await pg.mouse.down(); await pg.mouse.move(box.x+box.width*0.6, box.y+box.height*0.4,{steps:6}); await pg.mouse.up();
await pg.waitForTimeout(200);
const rects = await svg.locator('rect').count();
await pg.getByTitle('fechar').click({force:true}); await pg.waitForTimeout(200);
await pg.getByRole('button',{name:/Anotar/}).click({force:true}); await pg.waitForTimeout(200);
const rectsReabre = await pg.locator('svg[viewBox="0 0 1000 1414"]').first().locator('rect').count();
console.log('modal abriu:',abriu>0,'| retângulo desenhado:',rects,'| persistiu ao reabrir:',rectsReabre);
console.log('pageerrors:', errs.length?errs:'nenhum');
await b.close();
