import { chromium } from 'playwright-core';
const b=await chromium.launch({executablePath:'/opt/pw-browsers/chromium-1194/chrome-linux/chrome'});
const pg=await b.newPage({viewport:{width:1400,height:900}});
const errs=[]; pg.on('pageerror',e=>errs.push(e.message));
await pg.goto('http://localhost:4203/',{waitUntil:'networkidle'});
await pg.getByText('Entrar no painel').click({force:true});
await pg.getByRole('heading',{name:/Dashboard/}).waitFor({timeout:6000});
const go=async(label,head)=>{ await pg.locator('nav').getByRole('button',{name:new RegExp(label)}).click({force:true}); await pg.getByRole('heading',{name:head}).waitFor({timeout:6000}); };
await go('Produção','Kanban de Produção');
const antes=await pg.locator('.mono').filter({hasText:/PD00/}).count();
await go('Comercial','Comercial');
await pg.getByRole('button',{name:/Aprovar/}).first().click({force:true});
await pg.waitForTimeout(400);
await go('Produção','Kanban de Produção');
const depois=await pg.locator('.mono').filter({hasText:/PD00/}).count();
await go('Financeiro','Financeiro');
const baixa=await pg.getByRole('button',{name:/Baixar/}).count();
await go('Ficha','Ficha Técnica');
const refs=await pg.locator('tbody tr').count();
console.log('Kanban cards antes:',antes,'| depois de aprovar:',depois,'(esperado 6)');
console.log('Financeiro Baixar:',baixa,'| BOM linhas:',refs);
console.log('pageerrors:', errs.length?errs:'nenhum');
await b.close();
